-- MAX_LENGTH_PER_TYPE : 물고기 종류별 최대 길이 테이블
WITH MAX_LENGTH_PER_TYPE AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
),
-- FILTERED_FISH : max 길이를 가진 물고기들의 정보 테이블
FILTERED_FISH AS (
    SELECT *
    FROM FISH_INFO
    WHERE (FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE, MAX_LENGTH FROM MAX_LENGTH_PER_TYPE
    )
)

SELECT
    FI.ID,
    FNI.FISH_NAME,
    FI.LENGTH
FROM FILTERED_FISH FI
JOIN FISH_NAME_INFO FNI
    ON FI.FISH_TYPE = FNI.FISH_TYPE
ORDER BY FI.ID;